=== YaxcheAl/24_25-LEMA-PROYECTOXML-ALVAREZ/pagina_web/DTD/tienda_discos.dtd
<!ELEMENT tienda_discos (informacion_tienda,discos,formatos,artistas_discos,generos)>
<!ELEMENT informacion_tienda (nombre_tienda,direccion,horarios,contacto)>
<!ELEMENT nombre_tienda (#PCDATA)>
<!ELEMENT direccion (calle,ciudad,pais,codigo_postal)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT horarios (lunes,martes,miercoles,jueves,viernes,sabado,domingo)>
<!ELEMENT lunes (#PCDATA)>
<!ELEMENT martes (#PCDATA)>
<!ELEMENT miercoles (#PCDATA)>
<!ELEMENT jueves (#PCDATA)>
<!ELEMENT viernes (#PCDATA)>
<!ELEMENT sabado (#PCDATA)>
<!ELEMENT domingo (#PCDATA)>
<!ELEMENT contacto (telefono,email,web)>
<!ELEMENT telefono (#PCDATA)>

<!-- 2 CAMBIO-->
<!ATTLIST telefono direccion (movil|fijo) #REQUIRED>
<!ELEMENT email (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ELEMENT discos (disco+)>
<!ELEMENT disco (nombre_disco,autor?,fecha_lanzamiento,duracion,caratula,link_compra,canciones)>
<!ATTLIST disco cod_disco ID #REQUIRED>
<!ATTLIST disco cod_artista IDREF #REQUIRED>
<!ATTLIST disco cod_gen CDATA #IMPLIED>
<!ATTLIST disco cod_form  CDATA #IMPLIED>
<!-- 3 CAMBIO-->

<!ELEMENT nombre_disco (#PCDATA)>
<!ELEMENT fecha_lanzamiento (#PCDATA)>

<!-- CAMBIO 1 -->
<!ELEMENT duracion (#PCDATA)>
<!ATTLIST duracion medida CDATA #FIXED "minuto">

<!-- CAMBIO 3-->
<!ELEMENT formato (#PCDATA|nombre|descripcion)*>
<!ATTLIST formato cod_form (VINILO | CD | BLU-RAY) #REQUIRED>

<!ELEMENT caratula (#PCDATA)>
<!ELEMENT link_compra (#PCDATA)>
<!ELEMENT canciones (cancion+)>
<!ELEMENT cancion (titulo,duracion)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT formatos (formato+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT artistas_discos (artista+)>
<!ELEMENT artista (name,anyo_debut,lugar_origen,miembros)>
<!ATTLIST artista cod_artista ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT anyo_debut (#PCDATA)>
<!ELEMENT lugar_origen (#PCDATA)>
<!ELEMENT miembros (miembro+)>
<!ELEMENT miembro (#PCDATA)>

<!-- CAMBIO 4-->
<!ATTLIST miembro papel  (PRINCIPAL | OTRO) #REQUIRED>
<!ELEMENT generos (genero+)>


<!-- 5 CAMBIO -->
<!ATTLIST nombre_g conocido ( SI | NO) "SI" >

<!ELEMENT genero (nombre_g, descripcion)>
<!ATTLIST genero cod_gen ID #REQUIRED>
<!ELEMENT nombre_g (#PCDATA)>

=== YaxcheAl/24_25-LEMA-PROYECTOXML-ALVAREZ/pagina_web/DTD/tienda_discos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tienda_discos SYSTEM "tienda_discos.dtd">
<tienda_discos>
    <informacion_tienda>
        <nombre_tienda>NOMBRE A ELEGIR</nombre_tienda>
        <direccion>
            <calle>Avenida de la MÃºsica, 123</calle>
            <ciudad>Vitoria</ciudad>
            <pais>Spain</pais>
            <codigo_postal>28001</codigo_postal>
        </direccion>
        <horarios>
            <lunes>10:00 - 19:00</lunes>
            <martes>10:00 - 19:00</martes>
            <miercoles>10:00 - 19:00</miercoles>
            <jueves>10:00 - 19:00</jueves>
            <viernes>10:00 - 19:00</viernes>
            <sabado>11:00 - 14:00</sabado>
            <domingo>Cerrado</domingo>
        </horarios>
        <contacto>
            <telefono direccion="movil">+34 912 345 678</telefono>
            <email>contacto@discosrockpop.com</email>
            <web>www.discosrockpop.com</web>
        </contacto>
    </informacion_tienda>
    <discos>
        <disco cod_disco="C01" cod_artista="A10" cod_gen="G01" cod_form="CD" especial="SI">
            <nombre_disco>All Hope Is Gone</nombre_disco>
            <fecha_lanzamiento>2008-08-26</fecha_lanzamiento> 
            <duracion medida="minuto">57:44</duracion>
            <caratula>allhopeisgone-slipknot.jpg</caratula>
            <link_compra>https://www.fnac.es/a218771/Slipknot-All-Hope-Is-Gone</link_compra>
            <canciones>
                <cancion>
                    <titulo>.execute.</titulo>
                    <duracion medida="minuto">1:48</duracion>
                </cancion>
                <cancion>
                    <titulo>Gematria &#40;The Killing Name&#41;</titulo>
                    <duracion medida="minuto">6:01</duracion>
                </cancion>
                <cancion>
                    <titulo>Sulfur</titulo>
                    <duracion medida="minuto">4:37</duracion>
                </cancion>
                <cancion>
                    <titulo>Psychosocial</titulo>
                    <duracion medida="minuto">4:43</duracion>
                </cancion>
                <cancion>
                    <titulo>Dead Memories</titulo>
                    <duracion medida="minuto">4:28</duracion>
                </cancion>
                <cancion>
                    <titulo>Vendetta</titulo>
                    <duracion medida="minuto">5:15 </duracion>
                </cancion>
                <cancion>
                    <titulo>Butcher&#39;s Hook</titulo>
                    <duracion medida="minuto">4:14</duracion>
                </cancion>
                <cancion>
                    <titulo>Gehenna</titulo>
                    <duracion medida="minuto">6:53</duracion>
                </cancion>
                <cancion>
                    <titulo>This Cold Black</titulo>
                    <duracion medida="minuto">4:40</duracion>
                </cancion>
                <cancion>
                    <titulo>Wherein Lies Continue</titulo>
                    <duracion medida="minuto">5:36</duracion>
                </cancion>
                <cancion>
                    <titulo>Snuff</titulo>
                    <duracion medida="minuto">4:36</duracion>
                </cancion>
                <cancion>
                    <titulo>All Hope Is Gone</titulo>
                    <duracion medida="minuto">4:44</duracion>
                </cancion>
                <cancion>
                    <titulo>Child of Burning Time</titulo>
                    <duracion medida="minuto">5:09</duracion>
                </cancion>
                <cancion>
                    <titulo>Vermilion, PT. 2 &#40;Bloodstone Mix&#41;</titulo>
                    <duracion medida="minuto">3:39</duracion>
                </cancion>
                <cancion>
                    <titulo>&#39;Til We Die</titulo>
                    <duracion medida="minuto">5:45</duracion>
                </cancion>
            </canciones>
        </disco>
        <disco cod_disco="C02" cod_artista="A04" cod_gen="G03" cod_form="VINILO">
            <nombre_disco>Venom</nombre_disco>
            <fecha_lanzamiento>2008-08-14</fecha_lanzamiento>
            <duracion medida="minuto">57:44</duracion>
            <caratula>venom-bulletformyvalentine.jpg</caratula>
            <link_compra>https://www.emp-online.es/p/The-poison/574199St.html/?gQT=2</link_compra>
            <canciones>
                <cancion>
                    <titulo>Venom</titulo>
                    <duracion medida="minuto">1:26</duracion>
                </cancion>
                <cancion>
                    <titulo>No Way Out </titulo>
                    <duracion medida="minuto">3:53</duracion>
                </cancion>
                <cancion>
                    <titulo>Army of Noise</titulo>
                    <duracion medida="minuto">4:18</duracion>
                </cancion>
                <cancion>
                    <titulo>Worthless</titulo>
                    <duracion medida="minuto">3:18</duracion>
                </cancion>
                <cancion>
                    <titulo>You Want a Battle?</titulo>
                    <duracion medida="minuto">4:14</duracion>
                </cancion>
                <cancion>
                    <titulo>Broken</titulo>
                    <duracion medida="minuto">3:39</duracion>
                </cancion>
                <cancion>
                    <titulo>Venom</titulo>
                    <duracion medida="minuto">3:54</duracion>
                </cancion>
                <cancion>
                    <titulo>The Harder the Heart (The Harder It Breaks)</titulo>
                    <duracion medida="minuto">4:00</duracion>
                </cancion>
                <cancion>
                    <titulo>Skin</titulo>
                    <duracion medida="minuto">3:59</duracion>
                </cancion>
                <cancion>
                    <titulo>Hell or High Water</titulo>
                    <duracion medida="minuto">4:36</duracion>
                </cancion>
                <cancion>
                    <titulo>Pariah</titulo>
                    <duracion medida="minuto">3:46</duracion>
                </cancion>
            </canciones>
        </disco>
        <disco cod_disco="C03" cod_artista="A02" cod_gen="G02" cod_form="BLU-RAY" especial="SI">
            <nombre_disco>Music of My Mind</nombre_disco>
            <fecha_lanzamiento>1972-03-03</fecha_lanzamiento>
            <duracion medida="minuto">39:14</duracion>
            <caratula>Music_of_My_Mind.jpg</caratula>
            <link_compra>https://www.amazon.com/dp/B000002P0U</link_compra>
            <canciones>
                <cancion>
                    <titulo>Love Having You Around</titulo>
                    <duracion medida="minuto">3:30</duracion>
                </cancion>

                <cancion>
                    <titulo>Superwoman (Where Were You When I Needed You)</titulo>
                    <duracion medida="minuto">4:10</duracion>
                </cancion>

                <cancion>
                    <titulo>I Love Every Little Thing About You</titulo>
                    <duracion medida="minuto">3:35</duracion>
                </cancion>

                <cancion>
                    <titulo>Sweet Little Girl</titulo>
                    <duracion medida="minuto">3:19</duracion>
                </cancion>

                <cancion>
                    <titulo>Happier Than the Morning Sun</titulo>
                    <duracion medida="minuto">5:29</duracion>
                </cancion>

                <cancion>
                    <titulo>Girl Blue</titulo>
                    <duracion medida="minuto">4:46</duracion>
                </cancion>

                <cancion>
                    <titulo>Seems So Long</titulo>
                    <duracion medida="minuto">3:40</duracion>
                </cancion>

                <cancion>
                    <titulo>Keep on Running</titulo>
                    <duracion medida="minuto">4:45</duracion>
                </cancion>

                <cancion>
                    <titulo>Who&#39;s the One</titulo>
                    <duracion medida="minuto">3:45</duracion>
                </cancion>
            </canciones>
        </disco>
        <disco cod_disco="C04" cod_artista="A01" cod_gen="G02" cod_form="CD">
            <nombre_disco>The Definitive Collection</nombre_disco>
            <fecha_lanzamiento>2008-11-04</fecha_lanzamiento>
            <duracion medida="minuto">78:42</duracion>
            <caratula>The_Definitive_Collection.jpg</caratula>
            <link_compra>https://www.amazon.com/dp/B001A6H0Q6</link_compra>
            <canciones>
                <cancion>
                    <titulo>Fallin&#39;</titulo>
                    <duracion medida="minuto">3:29</duracion>
                </cancion>

                <cancion>
                    <titulo>If I Ain&#39;t Got You</titulo>
                    <duracion medida="minuto">3:49</duracion>
                </cancion>

                <cancion>
                    <titulo>My Boo</titulo>
                    <duracion medida="minuto">4:12</duracion>
                </cancion>

                <cancion>
                    <titulo>Girl on Fire</titulo>
                    <duracion medida="minuto">3:44</duracion>
                </cancion>

                <cancion>
                    <titulo>Un-Thinkable (I&#39;m Ready)</titulo>
                    <duracion medida="minuto">4:38</duracion>
                </cancion>

                <cancion>
                    <titulo>No One</titulo>
                    <duracion medida="minuto">4:13</duracion>
                </cancion>

                <cancion>
                    <titulo>Empire State of Mind (Part II) Broken Down</titulo>
                    <duracion medida="minuto">3:33</duracion>
                </cancion>
